[package]
name = "sefenbu"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
clap = { version = "4.5.29", features = ["derive"] }
image = "0.25.5"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
